/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.airlinesproject;

import javax.swing.*;

/**
 * The Login class represents a login form for authentication purposes.
 * It allows users to enter their username and password to access the system.
 *
 * <p>Usage:</p>
 * <pre>{@code
 * Login login = new Login();
 * login.setVisible(true);
 * }</pre>
 *
 * @author Ester
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login.
     */
    public Login() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        // Component initialization code (auto-generated)
    }
    // </editor-fold>

    /**
     * Handle mouse click event on the login button.
     * Validates the entered username and password.
     * If correct, opens the main form; otherwise, displays an error message.
     * Clears the fields if login fails.
     *
     * @param evt The MouseEvent that triggered the event.
     */
    private void login_buttonMouseClicked(java.awt.event.MouseEvent evt) {
        if (username.getText().isEmpty() || password.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter username and password");
        } else if (username.getText().equals("admin") && password.getText().equals("admin")) {
            new MainForm().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Incorrect username or password");
            username.setText(null);
            password.setText(null);
        }
    }

    /**
     * Handle mouse click event on the exit label.
     * Exits the application when clicked.
     *
     * @param evt The MouseEvent that triggered the event.
     */
    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {
        System.exit(0);
    }

    /**
     * Main method to start the login form.
     *
     * @param args The command line arguments.
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                     UnsupportedLookAndFeelException ex) {
                // Handle exception if look and feel cannot be set
            }

            Login login = new Login();
            login.setVisible(true);
        });

    }


    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private com.mycompany.airlinesproject.RoundedButton login_button;
    private com.mycompany.airlinesproject.PasswordField password;
    private com.mycompany.airlinesproject.FTextField username;

}
